lxc/lxc-templates

templates/lxc-opensuse.in

We add support for the newly released openSUSE Leap 15. Moreover we fix
some indentation issues and also switch the default distro to Leap 15
since 42.1 has been EOL'd long time ago.

templates: opensuse: Add support for openSUSE Leap 15

---

templates/lxc-plamo.in

Now, 7.x is our stable version.
Signed-off-by: KATOH Yasufumi <karma@jazz.email.ne.jp>

plamo: Update the default version to 7.x

---

templates/lxc-plamo.in

Signed-off-by: KATOH Yasufumi <karma@jazz.email.ne.jp>

plamo: Workaround for building plamo 32bit 6.x container on current 7.x

---

templates/lxc-slackware.in

Two more packages: libpsl and pcre2.
These libraries are needed by wget command, which is used in the built-in package manager, slackpkg.
Signed-off-by: CCHsu <a12321aabb@gmail.com>

Add new dependency for wget for lxc-slackware template

---

templates/lxc-debian.in

mkdir -p should create the dirname of the interpreter, not its basename.
Signed-off-by: Anders Oleson <anders-code@users.noreply.github.com>
fixes #26

lxc-debian: fix incorrect use of basename instead of dirname

---

templates/lxc-debian.in

[lxc-debian] Handle languages that are only UTF-8 encoded

---

templates/lxc-debian.in
templates/lxc-kali.in

replaces: #29
Various improvements and bugfixes for debian and kali templates figured out or taken from the work of Greg Olsen.
Little note, in last merge with a kali template repo you didn't add lxc-kali in templates/Makefile.am and kali common/userns configs to config/Makefile.am. You also didn't change permissions of templates/lxc-kali.in from 755 to 644
I don't know if it's intentional or not, in doubt I didn't change anything and just advised

Improvements and bugfixes to templates/lxc-devuan.in and templates/lxc-kali.in

---

templates/lxc-debian.in
templates/lxc-devuan.in
templates/lxc-kali.in

Devuan GPG keys has been copied into a position independent from current git engine

Changed devuan gpg key remote location

---

templates/lxc-plamo.in

pkgtool, that is package manager for plamo, has been updated. The
package name is changed to pkgtools8, and change installation process
to match pkgtools8.
Signed-off-by: KATOH Yasufumi <karma@jazz.email.ne.jp>

plamo: Support new pkgtools8

---

templates/lxc-debian.in

Addressing issue #39 where the Debian security distribution field is incorrect for the lxc-debian template.
Signed-off-by: Matthew Bruzek <mbruzek@gmail.com>

Changed security distribution to ${release}-security.

---

templates/lxc-alpine.in

This fixes a couple issues that prevents building alpine containers. First, we set a better list of apk keys to use for verification of bootstrap packages. Then we removed extra `mknod` calls to create character devices, and let lxc config handle this at container start (fixes #43).

Fix alpine lxc build

---

templates/lxc-gentoo.in

Gentoo uses arm64 in the download path. See
http://distfiles.gentoo.org/releases/arm64/autobuilds/

templates/lxc-gentoo.in: Propperly handle aarch64.

---

templates/lxc-debian.in

When the `--keyring` option was added in eebcd76feb47, the `,` between `mirror:` and `keyring:` was omitted in the long option string passed to `getopt`. This causes `--mirror` to be parsed as `--mirror:keyring`, matching `*) break ;;` and prematurely terminating option parsing.  To avoid this, add the missing `,`.  Also order `keyring:` before `mirror:` to preserve lexical ordering of long options.
Thanks for considering,
Kevin

lxc-debian: fix getopt parsing of --mirror

---

templates/lxc-voidlinux.in

voidlinux.eu has not been under Void Linux's control for over 4 years: https://voidlinux.org/news/2019/02/voidlinux-eu-gone.html
no clue if the script still works otherwise, I just noticed the urls were wrong

lxc-voidlinux.in: correct repo and docs urls

---

templates/lxc-debian.in

An official architecture is not always available in testing. New architectures get added to unstable first, and only some time after that they *may* get added to testing as well. This is just now happening with riscv64, and checking whether it's available in testing will *not* give the correct answer for the question "is this an official Debian architecture?".
Also, since debian-ports only contain unstable, just refuse to use debian-ports if not creating an unstable/sid container.

lxc-debian: improve detection of official architectures

---

Makefile.am

I think this is leftover from when lxc-templates was split out from lxc. There's no need to install empty directories /var/cache/lxc/ and /var/lib/lxc/.

Don't install empty directories

---

templates/lxc-alpine.in

On a Debian sid system with lxc 5.0.3 and the latest snapshot of lxc-templates, attempting to create an alpine container fails with the error "mknod: dev/console: File exists". This had been reported a while back in Debian bug [#998095](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=998095) and partially addressed in #46.
I performed some testing of the resulting alpine container, and things appear to be working correctly.

Fix alpine template

---

templates/lxc-debian.in
templates/lxc-kali.in

Plus some minor changes in lxc-kali. Thanks.

Support for non-free-firmware for Kali and Debian

---

templates/lxc-debian.in

It is still possible to create containers for jessie and stretch, although you need to manually specify the archive mirror and keyring:
lxc-create -t debian -n stretch -- -r stretch \
--mirror=http://archive.debian.org/debian \
--keyring=/usr/share/keyrings/debian-archive-removed-keys.gpg
While the jessie container starts up, it doesn't automatically get an IP -- I didn't perform any further investigation. stretch works just fine.
Debian releases wheezy and earlier fail to create the container in various ways.
This commit just changes the presented list of releases; there is some existing logic for handling archived releases, but I didn't want to risk breaking things by tinkering with the existing code.

Update the list of Debian releases that work out of the box

---

templates/lxc-alpine.in

This PR improves the integrity checking of the statically linked package manager executable (`apk.static`):
* Do not crash when a SHA256 signature file is present.
* Prefer the SHA256 signature to SHA1 when present.
* Delete the file on verification failure (to prevent it from becoming the default APK executable on the next run).

lxc-alpine: Improve integrity checking of static package manager
